# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: git config credential.helper 'cache --timeout=120'
      - run: git config user.email "liyanjia92@gmail.com"
      - run: git config user.name "Publish Bot"
      - run:
          name: Increment version
          command: npm version patch -m "Publish [skip ci]"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm run build
      - run: npm pack
      - run: tar -xvzf react-fast-highlighter-1.1.7.tgz
      - run:
          name: Publish package
          command: npm publish
      - run: git push -q https://${GITHUB_TOKEN}@github.com/ethanyanjiali/react-fast-highlighter.git master



